// Code generated by goctl. DO NOT EDIT.
// Source: follow.proto

package followerservice

import (
	"context"

	"MiniDY/app/social/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DouyinRelationActionRequest        = pb.DouyinRelationActionRequest
	DouyinRelationActionResponse       = pb.DouyinRelationActionResponse
	DouyinRelationFollowListRequest    = pb.DouyinRelationFollowListRequest
	DouyinRelationFollowListResponse   = pb.DouyinRelationFollowListResponse
	DouyinRelationFollowerListRequest  = pb.DouyinRelationFollowerListRequest
	DouyinRelationFollowerListResponse = pb.DouyinRelationFollowerListResponse
	DouyinRelationFriendListRequest    = pb.DouyinRelationFriendListRequest
	DouyinRelationFriendListResponse   = pb.DouyinRelationFriendListResponse

	Followerservice interface {
		// 关系操作
		RelationAction(ctx context.Context, in *DouyinRelationActionRequest, opts ...grpc.CallOption) (*DouyinRelationActionResponse, error)
		// 用户关注列表
		UserFollowList(ctx context.Context, in *DouyinRelationFollowListRequest, opts ...grpc.CallOption) (*DouyinRelationFollowListResponse, error)
		// 用户粉丝列表
		UserFollowerList(ctx context.Context, in *DouyinRelationFollowerListRequest, opts ...grpc.CallOption) (*DouyinRelationFollowerListResponse, error)
		// 用户好友列表
		UserFriendList(ctx context.Context, in *DouyinRelationFriendListRequest, opts ...grpc.CallOption) (*DouyinRelationFriendListResponse, error)
	}

	defaultFollowerservice struct {
		cli zrpc.Client
	}
)

func NewFollowerservice(cli zrpc.Client) Followerservice {
	return &defaultFollowerservice{
		cli: cli,
	}
}

// 关系操作
func (m *defaultFollowerservice) RelationAction(ctx context.Context, in *DouyinRelationActionRequest, opts ...grpc.CallOption) (*DouyinRelationActionResponse, error) {
	client := pb.NewFollowerserviceClient(m.cli.Conn())
	return client.RelationAction(ctx, in, opts...)
}

// 用户关注列表
func (m *defaultFollowerservice) UserFollowList(ctx context.Context, in *DouyinRelationFollowListRequest, opts ...grpc.CallOption) (*DouyinRelationFollowListResponse, error) {
	client := pb.NewFollowerserviceClient(m.cli.Conn())
	return client.UserFollowList(ctx, in, opts...)
}

// 用户粉丝列表
func (m *defaultFollowerservice) UserFollowerList(ctx context.Context, in *DouyinRelationFollowerListRequest, opts ...grpc.CallOption) (*DouyinRelationFollowerListResponse, error) {
	client := pb.NewFollowerserviceClient(m.cli.Conn())
	return client.UserFollowerList(ctx, in, opts...)
}

// 用户好友列表
func (m *defaultFollowerservice) UserFriendList(ctx context.Context, in *DouyinRelationFriendListRequest, opts ...grpc.CallOption) (*DouyinRelationFriendListResponse, error) {
	client := pb.NewFollowerserviceClient(m.cli.Conn())
	return client.UserFriendList(ctx, in, opts...)
}
