// Code generated by goctl. DO NOT EDIT.
// Source: interacts.proto

package server

import (
	"context"

	"MiniDY/app/interaction/cmd/rpc/internal/logic"
	"MiniDY/app/interaction/cmd/rpc/internal/svc"
	"MiniDY/app/interaction/cmd/rpc/pb"
)

type InteractsserviceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedInteractsserviceServer
}

func NewInteractsserviceServer(svcCtx *svc.ServiceContext) *InteractsserviceServer {
	return &InteractsserviceServer{
		svcCtx: svcCtx,
	}
}

// 点赞
func (s *InteractsserviceServer) VideoInteraction(ctx context.Context, in *pb.DouyinFavoriteActionRequest) (*pb.DouyinFavoriteActionResponse, error) {
	l := logic.NewVideoInteractionLogic(ctx, s.svcCtx)
	return l.VideoInteraction(in)
}

// 喜欢列表
func (s *InteractsserviceServer) VideoInteractionList(ctx context.Context, in *pb.DouyinFavoriteListRequest) (*pb.DouyinFavoriteListResponse, error) {
	l := logic.NewVideoInteractionListLogic(ctx, s.svcCtx)
	return l.VideoInteractionList(in)
}

// 评论
func (s *InteractsserviceServer) VideoCommentAction(ctx context.Context, in *pb.DouyinCommentActionRequest) (*pb.DouyinCommentActionResponse, error) {
	l := logic.NewVideoCommentActionLogic(ctx, s.svcCtx)
	return l.VideoCommentAction(in)
}

// 评论列表
func (s *InteractsserviceServer) VideoCommentList(ctx context.Context, in *pb.DouyinCommentListRequest) (*pb.DouyinCommentListResponse, error) {
	l := logic.NewVideoCommentListLogic(ctx, s.svcCtx)
	return l.VideoCommentList(in)
}
