// Code generated by goctl. DO NOT EDIT.
// Source: video.proto

package server

import (
	"context"

	"MiniDY/app/videos/cmd/rpc/internal/logic"
	"MiniDY/app/videos/cmd/rpc/internal/svc"
	"MiniDY/app/videos/cmd/rpc/pb"
)

type VideoserviceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedVideoserviceServer
}

func NewVideoserviceServer(svcCtx *svc.ServiceContext) *VideoserviceServer {
	return &VideoserviceServer{
		svcCtx: svcCtx,
	}
}

// 获取视频流
func (s *VideoserviceServer) GetVideoFeed(ctx context.Context, in *pb.DouyinFeedRequest) (*pb.DouyinFeedResponse, error) {
	l := logic.NewGetVideoFeedLogic(ctx, s.svcCtx)
	return l.GetVideoFeed(in)
}

// 视频投稿
func (s *VideoserviceServer) PublishVideoList(ctx context.Context, in *pb.DouyinPublishListRequest) (*pb.DouyinPublishListResponse, error) {
	l := logic.NewPublishVideoListLogic(ctx, s.svcCtx)
	return l.PublishVideoList(in)
}
