// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"MiniDY/app/social/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/action",
				Handler: relationactionHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/follow/list",
				Handler: followListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/follower/list",
				Handler: followerListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/friend/list",
				Handler: FriendsListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/douyin/relation"),
	)
}
